name: kroenchen_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  intl: ^0.19.0
  ionicons: ^0.2.2
  shared_preferences: ^2.3.3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black900.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Bold700.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold800.ttf
          weight: 800
        - asset: assets/fonts/Outfit-ExtraLight200.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light300.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Medium500.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular400.ttf
          weight: 400
        - asset: assets/fonts/Outfit-SemiBold600.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Thin100.ttf
          weight: 100

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/Kroenchen_app_icon.png


